from typing import Protocol, Dict, Any

class Repository(Protocol):
    def save_analysis(self, payload: Dict[str, Any]) -> str: ...
    def get_analysis(self, id_: str) -> Dict[str, Any]: ...
    def list_examples(self) -> list[str]: ...
